# Generated by Django 4.1.3 on 2022-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_product_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
