# Generated by Django 4.1.3 on 2022-12-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_product_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.order'),
        ),
    ]
